"""initial schema

Revision ID: 6e29f70ddf52
Revises: 
Create Date: 2026-09-14 12:47:18.507170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e29f70ddf52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beaches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('shoreline_bearing', sa.Float(), nullable=True),
    sa.Column('obstruction_notes', sa.Text(), nullable=True),
    sa.Column('coordinate_source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buoys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('licence_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beach_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wave_height', sa.Float(), nullable=True),
    sa.Column('wave_direction', sa.Float(), nullable=True),
    sa.Column('wave_period', sa.Float(), nullable=True),
    sa.Column('swell_wave_height', sa.Float(), nullable=True),
    sa.Column('swell_wave_direction', sa.Float(), nullable=True),
    sa.Column('swell_wave_period', sa.Float(), nullable=True),
    sa.Column('wind_wave_height', sa.Float(), nullable=True),
    sa.Column('wind_wave_direction', sa.Float(), nullable=True),
    sa.Column('wind_wave_period', sa.Float(), nullable=True),
    sa.Column('wave_source_model', sa.String(length=32), nullable=True),
    sa.Column('wind_speed_10m', sa.Float(), nullable=True),
    sa.Column('wind_direction_10m', sa.Float(), nullable=True),
    sa.Column('wind_gusts_10m', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('backfilled', sa.Boolean(), nullable=False),
    sa.Column('wind_fetch_failed', sa.Boolean(), nullable=False),
    sa.Column('wave_fetch_failed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beach_id'], ['beaches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beach_id', 'issued_at', 'valid_at', name='uq_forecast_natural_key')
    )
    op.create_index('ix_forecast_latest', 'forecasts', ['beach_id', 'valid_at', 'issued_at'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buoy_id', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wave_height', sa.Float(), nullable=True),
    sa.Column('wave_period', sa.Float(), nullable=True),
    sa.Column('wave_max', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buoy_id'], ['buoys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buoy_id', 'observed_at', name='uq_measurement_natural_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_index('ix_forecast_latest', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('ingestion_runs')
    op.drop_table('buoys')
    op.drop_table('beaches')
    # ### end Alembic commands ###
